### PR TITLE
Making network_plot more robust

### PR DESCRIPTION
**Pull request by thisisdaryn**
Addresses [#106](https://github.com/tidymodels/corrr/issues/106) 

If the call to `stats::cmdscale` internal to `network_plot` does not return a matrix of 2 columns, uniform shifts are added to the off-diagonal entries of the distance matrix and another attempt is made. The search for the shift value iterates through a fixed list of possible values, 10^(-6:-1), before terminating.  

The error in the #106 arises at the point of trying to rename the first 2 columns of a matrix that has only one column.

Warnings from `stats::cmdscale` are not suppressed but they could be. As is, the end-user of network plot will see warnings for each call that does not return a matrix of 2 columns.

Test running with the data of #106 (The variables in the example data are highly-correlated):

```
> camas_desempleo %>%
+   select(-CCAA) %>%
+   correlate() %>%
+   network_plot()

Correlation method: 'pearson'
Missing treated using: 'pairwise.complete.obs'

Warning messages:
1: In stats::cmdscale(distance) :
  only 1 of the first 2 eigenvalues are > 0
2: In stats::cmdscale(shifted_distance) :
  only 1 of the first 2 eigenvalues are > 0
3: In stats::cmdscale(shifted_distance) :
  only 1 of the first 2 eigenvalues are > 0
4: In stats::cmdscale(shifted_distance) :
  only 1 of the first 2 eigenvalues are > 0
5: In stats::cmdscale(shifted_distance) :
  only 1 of the first 2 eigenvalues are > 0
6: In stats::cmdscale(shifted_distance) :
  only 1 of the first 2 eigenvalues are > 0

```

plot106

### CODE REVIEW

**Comment by juliasilge** [comment]
This looks really good, but I think we probably should give a more user-friendly warning about what is happening and why. Can you check out the [tidyverse style guide on error messages](https://style.tidyverse.org/error-messages.html) and add a different warning for these shifts? We should probably use [`rlang::warn()`](https://rlang.r-lib.org/reference/abort.html).

**Comment by juliasilge** [comment]
This is looking great! Let's do just one more little round of edits on the warning message itself. I suspect a typical user may think, "Wait, what has gone wrong?! I didn't give this function any matrix of coordinates???" 🤔 

What do you think could be a good option for a [slightly revamped message](https://style.tidyverse.org/error-messages.html)?

```
Coordinates created for plotting have dimension < 2.
Correlations have been shifted numerically to facilitate plotting.
```

```
Plot coordinates derived from correlation matrix have dimension < 2.
`correlate()` output has been adjusted to facilitate plotting.
```

Other ideas?

**Comment by thisisdaryn** [comment]
Idea: to tweak the latter option
```
Plot coordinates derived from correlation matrix have dimension < 2.
Pairwise distances have been adjusted to facilitate plotting.
```

This is a tricky question because the quantity being changed was an approximation anyway. 

I don't think it is correct to say either that the correlations have been shifted or that correlate() output has been adjusted. The correlations are being represented in the plot in 2 ways:
1. The correlations are mapped to the colors of the edges. This mapping is precise and specified in the plot's legend and is not affected by applying the shifts.
2. The distance between the nodes is based on a function of the correlation. These distances would almost certainly have been approximations even in cases where we don't have to apply these shifts. The shifts increase these distances. 

What we are really trying to convey is that the distances between the nodes have knowingly been increased in this instance.

**Comment by juliasilge** [comment]
I think that is fantastic. 👍 Let's go with that option.

**Comment by thisisdaryn** [comment]
Question: how important is it that we pass along/translate warnings from the base R function call internal to the function? 

The latest iteration of the PR suppresses a warning from a base R function and paraphrases it in the hope of being more helpful to the user who didn't call that function. So the number of warnings that get to the end-user is still the same as the total number of warnings i.e. one for each time a shift is applied (6 in this case).

Is it an option to provide a single warning to indicate that one or more attempts were made to find a shift distance that works?  I think this may be possible to articulate without detracting from the user's ability to locate the error.

**Comment by juliasilge** [comment]
Excellent! 🙌 

I see what you're saying about the repetition of the messages. My feeling is that it is _not_ that helpful for the user to see the same warning a bunch of times in this situation. What do you think about only showing the user the warning once, when one or more shifts has been changed?

**Comment by juliasilge** [comment]
Excellent! 🙌

Thank you so much for your work on this.

**Comment by juliasilge** [comment]
macOS R devel GH action builds are all broken right now, FWIW.

**Pull request merged**
