### PR TITLE
Support for arbitrary functions

### PR DESCRIPTION
**Pull request by jameslairdsmith**
This PR implements the ability to make column comparisons using the values generated from an arbitrary function. This is done with a new function called `colpair_map()`. It enables enhancements mentioned in #94, #44 and #42.

The implementation includes:

- A new .R file with the function and its documentation.
- A new vignette with more details of the function and how it can be used.
- Unit tests for the function.

## Function naming

I thought for a long time about what the function should be called. I settled on the idea `colpair_` because it's the closest thing I can think of that communicates the fact that this operation is being applied to "pairs" of "columns". "map" is inherited from purrr.

## Scoping

When I suggested the idea for the this function in #94,  @topepo raised the point (with which I agree) that we don't want to encourage too much scope creep.

That being said, I do think there is perhaps a case for making some helper functions. For example, because the covariance is likely to be a very common application (it has been requested in #42), we may have a helper called something like `colpair_cov()`. None of these are implemented in this PR, but I thought they were worth mentioning.

### CODE REVIEW

**Comment by juliasilge** [comment]
This looks fantastic @jameslairdsmith! 🙌  Thank you so much for your work on this.

One change we would like to make is to move the content included here as a vignette to a blog post on the [tidyverse blog](https://www.tidyverse.org/blog/) at the next corrr release. That's a better platform for showing off nice examples like this, especially if they involve other packages not related to the package code itself. Can you set aside the vignette code for now and remove those extra packages from `DESCRIPTION`? Let's get that published on the blog instead. 🚀

**Review by juliasilge — CHANGES_REQUESTED** [review]
Looking great! ✨ 

Changes still needed are:

- add a line to `NEWS` describing this change (follow existing format)
- remove vignette and added packages, to be used in blog post instead

**Comment by jameslairdsmith** [comment]
Thanks @juliasilge! I've made the changes as requested.

**Review by juliasilge — APPROVED** [review]

**Comment by juliasilge** [comment]
Thank you so much @jameslairdsmith! 💯 

Are you up for writing a blog post at the next CRAN release illustrating this new functionality? If you would prefer to do this on your own blog, that is fine with us, but it would be a great fit for the tidyverse blog as well.

**Comment by jameslairdsmith** [comment]
Thanks @juliasilge! I think a release announcement on the tidyverse blog would be a good place for this. I would be delighted to write it!

**Pull request merged**
